---
database:
  host: ""
  dbname: ""
  user: ""
  password: ""

policies:
- compression: "7 days"
  retention: "400 days"
  tables:
  - "metricName"
  - "metricTemplate_.*"
- compression: "7 days"
  retention: "30 days"
  tables:
  - "anotherMetricName"
  - "anotherMetricTemplate_.*"
- compression: "7 days"
  retention: "40 days"
  tables: ".*"
